### 对话
POST http://localhost:8000/chat/stream
Content-Type: application/json
Connection: keep-alive
user-token: user_123
chat-id: chat_4c279fe2-fb7a-40bf-b70c-9cf7604d0a12

{
  "content": "你今天吃饭了吗。请使用 greet 技能回复"
}

### 人工介入
POST http://localhost:8000/chat/stream
Content-Type: application/json
Connection: keep-alive
user-token: user_123
chat-id: chat_4c279fe2-fb7a-40bf-b70c-9cf7604d0a12

{
  "content": "将 hello 写入文件 hello.txt"
}

### 人工审批
POST http://localhost:8000/chat/stream
Content-Type: application/json
Connection: keep-alive
user-token: user_123
chat-id: chat_4c279fe2-fb7a-40bf-b70c-9cf7604d0a12

{
  "msg_type": "DECISION",
  "decision": {
    "decision_id": "a5f2f274d287c3173568a0319766d020",
    "items": [
      {
        "decision_type": "approve",
        "description": "同意"
      }
    ]
  }
}

### 访问 User agent
POST http://localhost:8000/chat/stream
Content-Type: application/json
Connection: keep-alive
user-token: user_123
chat-id: chat_4c279fe2-fb7a-40bf-b70c-9cf7604d0a12

{
  "content": "我叫 Alice，我的邮箱是 alice@example.com，爱好学习、写代码"
}
