### 访问 MCP 工具
POST http://localhost:8000/chat/stream
Content-Type: application/json
Connection: keep-alive
user-token: user_123
chat-id: chat_782e77c0-ddb6-45a7-b8ae-5c16a3f51916

{
  "content": "搜索下关于 Deepseek V3 的论文，总结 50 字给我"
}
