from agent.prompts.agent_prompts import *

__all__ = [
    "AGENT_PROMPT_MAIN",
    "AGENT_PROMPT_FILE_MANAGER",
    "AGENT_PROMPT_RESEARCH",
    "AGENT_PROMPT_REVIEW",
    "AGENT_PROMPT_WRITING",
    "AGENT_PROMPT_GREET",
    "AGENT_PROMPT_USER",
    "AGENT_DESCRIPTION_FILE_MANAGER",
    "AGENT_DESCRIPTION_RESEARCH",
    "AGENT_DESCRIPTION_WRITING",
    "AGENT_DESCRIPTION_REVIEW",
    "AGENT_DESCRIPTION_GREET",
    "AGENT_DESCRIPTION_USER",
]
